name: Sync Selected Files to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Prepare deploy folder
        run: |
          mkdir -p deploy/src/app/reports

          # copy Dockerfile
          cp Dockerfile deploy/

          # copy app code
          cp -r src/app/*.py deploy/src/app/

          # copy reports from root-level folder
          cp -r reports/* deploy/src/app/reports/ || true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd deploy

          git init
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          git remote add space https://huggingface.co/spaces/servisgas/pricing

          git add .
          git commit -m "Deploy selected files"
          git push --force https://zcemg08:$HF_TOKEN@huggingface.co/spaces/servisgas/pricing HEAD:main
